services:
  - type: web
    name: documind
    runtime: docker
    disk:
      name: chroma-sessions
      mountPath: /data/chroma_db_sessions
      sizeGB: 1
    healthCheckPath: /
    envVars:
      - key: CHROMA_DB_PATH
        value: /data/chroma_db_sessions
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: BUCKET_NAME
        sync: false
